name: CI Test Workflow

# Trigger the workflow on push, pull request, or manual trigger
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-on:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16.x]

    steps:
      # Step to check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js based on the matrix of versions and operating systems
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'  # Caching node_modules for faster builds

      # Install project dependencies using npm
      - name: Install Dependencies
        run: npm install

      # Run Tests
      - name: Run Tests
        run: npm test

      # Debugging step to gather logs if the test fails
      - name: Debugging logs
        if: failure()
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Node.js Version:"
          node -v
          echo "NPM Version:"
          npm -v
          echo "Installed dependencies:"
          npm ls
